/*
// Test for parallel I/O benchmark
// Written by Jean M. Favre, Swiss National Supercomputer Center
// Last update: Wed Jun 8 2011
*/
/*
// Attention: gwrite_writer3D.ch is autogenerated by "python gpp.py benchmark.xml"
*/
#include <stdio.h>
// #include <adios.h>

void ADIOS_WriteData(simulation_data *sim, char *Filename)
{

// make sure it divided evenly in the Z direction

  int         sb, i, j, k, f, adios_err;

  uint64_t    adios_groupsize, adios_totalsize;
  int64_t     adios_handle;
  int offs_x, offs_y, offs_z;
  //sprintf (sim->filename, "/scratch/eiger/jfavre/grid_%d.nc", sim->cycle);
  //if(sim->par_rank == 0) fprintf(stderr,"creating file %s\n", Filename);

  //adios_init ("/users/jfavre/Projects/ADIOS/benchmark.xml");

  adios_open (&adios_handle, "writer3D", Filename, "w", sim->comm_cart);

  offs_x = sim->grid.Ncolumns * sim->coords[0];
  offs_y = sim->grid.Nrows * sim->coords[1];
  offs_z = 0;

#include "gwrite_writer3D.ch"
  adios_close (adios_handle);
  //adios_finalize (sim->par_rank);
}

